fix: refactor and fix notAllAreUsed rule.
kubewarden/environment-variable-policy pull request #57
Opened 2024-12-20 20:57 UTC by jvanz

## Description

notAllAreUser rule was not allowing users to deploy resources with one of the environment variables defined. This commit fixes that.

The policy tests have been refactored and extended.

The README file has been update to properly state what which rule type does.

2025-01-03 15:50 UTC, viccuad commented on README.md
> +variables names and values. The policy allows the users define multiple
```suggestion
variables names and values. The policy allows the users to define multiple
```

2025-01-03 15:50 UTC, viccuad commented on src/lib.rs
> +            invalid_envvar.sort();
Same here.

2025-01-03 15:51 UTC, viccuad requested changes
Looks good, just some nitpicks.

2025-01-06 16:00 UTC, kravciak requested changes
Naming of rules is very confusing for me, even though I read description 5+ times.

For example:
 - negation is in switching position: anyNotIn ->notAllAreUsed
 - some have `AreUsed` suffix, why not `anyInAreUsed` (consistent but even more confusing)
 - notAllAreUsed name suggests `any missing` would fail, description says all have to be missing
 - anyNotIn name suggests it would fail if resource has any extra env var

What do you think about changing rule names & descriptions to this? This I could understand even without description.

```
anyIn → anyMatch
(Rejects if at least one of the specified environment variables is defined in the resource.)

anyNotIn → anyMissing
(Rejects if at least one of the specified environment variables is missing in the resource.)

allAreUsed → allMatch
(Rejects if all of the specified environment variables are defined in the resource.)

notAllAreUsed → allMissing
(Rejects if all of the specified environment variables are missing in the resource.)
```

2025-01-07 09:57 UTC, kravciak commented
I created new issue, you are right that it's out of scope of this PR.
https://github.com/kubewarden/environment-variable-policy/issues/59

2025-01-08 12:20 UTC, viccuad approved these changes
LGTM!

2025-01-08 17:04 UTC, flavio commented on README.md
> +  are **missing** in the  resource
I still find it confusing, this is not what I would expect.

The way I interpret it is: "anyNotIn" -> "anything not in". Hence if the values are `[1,2]`:

- 3 is true, because it's neither 1 or 2
- 1 is false, because it's part of the list

Going back to our policy. Assume the following configuration:

```yaml
settings:
  rules:
    - reject: anyNotIn
      environmentVariables:
        - name: "envvar2"
          value: "envvar2_value"
        - name: "envvar3"
```

A resource would be accepted if it has zero environment variables defined or if it has either `envvar2`, `envvar3` or both of them defined.

| Resource    | Result                                    |
| ---------- | ------------------------------------------ |
| uses `envvar2` and `envvar3` | accepted ✔️ |
| uses `envvar2` | accepted ✔️ |
| uses `envvar3` | accepted ✔️ |
| no env variable defined | accepted ✔️ |
| uses `envvar3` and `foo` |rejected ❌ | 
| uses `foo` |rejected ❌ |

2025-01-08 17:04 UTC, flavio commented on README.md
> +  are **missing** in the  resource
@kubewarden/kubewarden-developers what do you think?

2025-01-09 13:25 UTC, fabriziosestito commented on README.md
> +  are **missing** in the  resource
@flavio I agree with the above, I expect the `AnyNotIn` rule to reject anything outside what is specified in the `environmentVariables` list. 
I'm not sure to accept when no env variables are defined, but generally, I am fine with this behavior.

2025-01-10 07:35 UTC, flavio commented
I think this can be closed, since we've decided to change drastically how this policy behaves. See https://github.com/kubewarden/environment-variable-policy/issues/60

2025-01-10 07:35 UTC, closed without merging